//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NogometWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NogometWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj golova:.
        /// </summary>
        public static string brojGolova {
            get {
                return ResourceManager.GetString("brojGolova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjeda:.
        /// </summary>
        public static string brojPobjeda {
            get {
                return ResourceManager.GetString("brojPobjeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj poraza:.
        /// </summary>
        public static string brojPoraza {
            get {
                return ResourceManager.GetString("brojPoraza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to engleski.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabijenih golova:.
        /// </summary>
        public static string golovi {
            get {
                return ResourceManager.GetString("golovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrvatski.
        /// </summary>
        public static string hr {
            get {
                return ResourceManager.GetString("hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to muško.
        /// </summary>
        public static string musko {
            get {
                return ResourceManager.GetString("musko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad.
        /// </summary>
        public static string nazad {
            get {
                return ResourceManager.GetString("nazad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neodlučenih utakmica:.
        /// </summary>
        public static string neodlucenihUtakmica {
            get {
                return ResourceManager.GetString("neodlucenihUtakmica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite jezik:.
        /// </summary>
        public static string odaberiteJezik {
            get {
                return ResourceManager.GetString("odaberiteJezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite protivnika:.
        /// </summary>
        public static string odaberiteProtivnika {
            get {
                return ResourceManager.GetString("odaberiteProtivnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite prvenstvo:.
        /// </summary>
        public static string odaberitePrvenstvo {
            get {
                return ResourceManager.GetString("odaberitePrvenstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite reprezentaciju:.
        /// </summary>
        public static string odaberiteReprezentaciju {
            get {
                return ResourceManager.GetString("odaberiteReprezentaciju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite veličinu ekrana:.
        /// </summary>
        public static string odaberiteVelicinuEkrana {
            get {
                return ResourceManager.GetString("odaberiteVelicinuEkrana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabrana reprezentacija:.
        /// </summary>
        public static string odabranaReprezentacija {
            get {
                return ResourceManager.GetString("odabranaReprezentacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odigranih utakmica:.
        /// </summary>
        public static string odigranihUtakmica {
            get {
                return ResourceManager.GetString("odigranihUtakmica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string odustani {
            get {
                return ResourceManager.GetString("odustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija:.
        /// </summary>
        public static string pozicija {
            get {
                return ResourceManager.GetString("pozicija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži rezultat.
        /// </summary>
        public static string prikaziRezultat {
            get {
                return ResourceManager.GetString("prikaziRezultat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primljenih golova:.
        /// </summary>
        public static string primljenihGolova {
            get {
                return ResourceManager.GetString("primljenihGolova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlika:.
        /// </summary>
        public static string razlika {
            get {
                return ResourceManager.GetString("razlika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentacije.
        /// </summary>
        public static string reprezentacije {
            get {
                return ResourceManager.GetString("reprezentacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        public static string spremi {
            get {
                return ResourceManager.GetString("spremi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULAZ.
        /// </summary>
        public static string ulaz {
            get {
                return ResourceManager.GetString("ulaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to žensko.
        /// </summary>
        public static string zensko {
            get {
                return ResourceManager.GetString("zensko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj žutih kartona:.
        /// </summary>
        public static string zutihKartona {
            get {
                return ResourceManager.GetString("zutihKartona", resourceCulture);
            }
        }
    }
}
